language: r

sudo: false

before_install:
  - sh -e /etc/init.d/xvfb start

r_github_packages:
  - jimhester/covr
  - trinker/textshape
  - trinker/lexicon
  - trinker/textclean

notifications:
  email:
    on_success:      change
    on_failure:      change

after_success:
  - Rscript -e 'covr::coveralls()'

r_build_args: "--resave-data=best"
r_check_args: "--as-cran"

env:
   global:
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1


